name: Docker build & push

on:
  release:
    types:
      - "published"

jobs:
  build-push:
    name: Build and push the image
    runs-on: ubuntu-latest
    steps:
      - name: Get release name
        run: echo "RELEASE_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        id: get_release_name

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image with '${{ steps.get_release_name.outputs.RELEASE_NAME }}' tag
        uses: docker/build-push-action@v3.2.0
        with:
          tags: matijas05/odrabiamy-bot:${{ steps.get_release_name.outputs.RELEASE_NAME }}
          push: true
          build-args: |
            VERSION=${{ steps.get_release_name.outputs.RELEASE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push image with 'latest' tag
        uses: docker/build-push-action@v3.2.0
        with:
          tags: matijas05/odrabiamy-bot:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
